export const UNIVERSITIES: string[] = [
  "Federal University of Technology, Minna",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Owerri (FUTO)",
  "Covenant University",
  "Bells University of Technology",
  "University of Ibadan",
  "University of Lagos",
  "Obafemi Awolowo University",
  "Ahmadu Bello University",
  "University of Nigeria, Nsukka",
  "University of Benin",
  "University of Ilorin",
  "University of Uyo",
  "University of Jos",
  "University of Maiduguri",
  "Lagos State University (LASU)",
  "Rivers State University",
  "Afe Babalola University",
  "Babcock University",
  "Pan-Atlantic University",
  "MIT",
  "Stanford University",
  "Caltech",
  "ETH Zurich",
  "Imperial College London",
  "Tsinghua University",
  "National University of Singapore",
  "University of Cambridge",
  "University of Oxford",
  "Nanyang Technological University",
  "Peking University",
  "University of Tokyo",
  "Technical University of Munich",
  "Georgia Tech",
  "Carnegie Mellon University",
  "University of British Columbia",
  "University of Toronto",
  "EPFL (Lausanne)",
  "KAIST (Korea)",
  "Delft University of Technology",
  "University of Melbourne",
  "University of Sydney",
  "University of Edinburgh",
  "McGill University",
  "University of Washington",
  "University of California, Berkeley",
  "University of Illinois Urbana-Champaign",
  "Purdue University",
  "University of Texas at Austin",
  "Hong Kong University of Science & Technology",
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Johns Hopkins University",
  "University of Chicago",
  "Cornell University",
  "University of Michigan",
  "University of California, Los Angeles (UCLA)",
  "New York University (NYU)",
  "Northwestern University",
  "Duke University",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of North Carolina at Chapel Hill",
  "Boston University",
  "University of Southern California",
  "University of Wisconsin–Madison",
  "University of Minnesota",
  "Ohio State University",
  "Pennsylvania State University",
  "University of Florida",
  "University of Maryland",
  "University of Rochester",
  "University of Colorado Boulder",
  "University of Pittsburgh",
  "Michigan State University",
  "Indiana University Bloomington",
  "University of Arizona",
  "Arizona State University",
  "University of Utah",
  "University of Kansas",
  "University of Iowa",
  "University of Oregon",
  "University of Alabama",
  "University of Massachusetts Amherst",
  "Stony Brook University",
  "University at Buffalo (SUNY)",
  "University of Texas at Dallas",
  "University of Texas at Arlington",
  "University of Illinois at Chicago",
  "University of California, Riverside",
  "University of California, Santa Cruz",
  "University of Copenhagen",
  "University of Helsinki",
  "University of Oslo",
  "Stockholm University",
  "Lund University",
  "University of Amsterdam",
  "Leiden University",
  "Utrecht University",
  "KU Leuven",
  "Ghent University",
  "University of Paris-Saclay",
  "Sorbonne University",
  "University of Barcelona",
  "University of Vienna",
  "University of Zurich",
  "University of Geneva",
  "Ludwig Maximilian University of Munich",
  "Humboldt University of Berlin",
  "Free University of Berlin",
  "RWTH Aachen University",
  "Heidelberg University",
  "University of Bologna",
  "Sapienza University of Rome",
  "University of Warsaw",
  "Charles University",
  "University of São Paulo",
  "University of Buenos Aires",
  "National Autonomous University of Mexico (UNAM)",
  "University of Chile",
  "University of Cape Town",
  "University of the Witwatersrand",
  "University of Pretoria",
  "University of Auckland",
  "University of Queensland",
  "Australian National University (ANU)",
  "Monash University",
  "University of New South Wales (UNSW Sydney)",
  "University of Western Australia",
  "University of Adelaide",
  "University of Hong Kong (HKU)",
  "Chinese University of Hong Kong (CUHK)",
  "City University of Hong Kong",
  "University of Science and Technology of China (USTC)",
  "Zhejiang University",
  "Shanghai Jiao Tong University",
  "Fudan University",
  "Nanjing University",
  "Seoul National University",
  "Yonsei University",
  "Korea University",
  "Kyoto University",
  "Osaka University",
  "Tohoku University",
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi"
]